# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20190807-YaseenAlDallash-NYCSchools' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20190807-YaseenAlDallash-NYCSchools

  target '20190807-YaseenAlDallash-NYCSchoolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20190807-YaseenAlDallash-NYCSchoolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
